# Generated by Django 5.2 on 2026-07-08 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUiModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='模块级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_ui_modules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_ui_automation.appuimodule', verbose_name='父模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_ui_modules', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'APPUI 模块',
                'verbose_name_plural': 'APPUI 模块',
                'db_table': 'app_ui_module',
                'ordering': ['project', 'level', 'name'],
                'unique_together': {('project', 'parent', 'name')},
            },
        ),
    ]
