# Generated by Django 5.2 on 2026-07-08 04:22

import app_ui_automation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ui_automation', '0001_initial'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUiScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='脚本名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='脚本描述')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10, verbose_name='目标平台')),
                ('script_file', models.FileField(help_text='上传 .air 目录打包的 zip 文件', upload_to=app_ui_automation.models.app_ui_script_path, verbose_name='Airtest脚本包')),
                ('script_dir', models.CharField(blank=True, default='', max_length=500, verbose_name='脚本目录路径')),
                ('script_entry', models.CharField(blank=True, default='', max_length=255, verbose_name='脚本入口文件')),
                ('level', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=2, verbose_name='用例等级')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='idle', max_length=10, verbose_name='最近状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_ui_scripts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='app_ui_automation.appuimodule', verbose_name='所属模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_ui_scripts', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'APPUI 脚本',
                'verbose_name_plural': 'APPUI 脚本',
                'db_table': 'app_ui_script',
                'ordering': ['-created_at'],
            },
        ),
    ]
