# Generated by Django 5.2 on 2026-07-14 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('content', models.TextField(help_text='Markdown格式，支持{{变量}}占位符', verbose_name='模板内容')),
                ('platform_type', models.CharField(choices=[('feishu', '飞书')], default='feishu', max_length=20, verbose_name='平台类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_message_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '消息模板',
                'verbose_name_plural': '消息模板',
                'ordering': ['-is_system', '-created_at'],
            },
        ),
    ]
