# Generated by Django 5.2 on 2026-07-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_messagetemplate'),
        ('task_center', '0008_scheduledtask_app_ui_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='push_config',
            field=models.CharField(choices=[('always', '总是推送'), ('failure_only', '仅失败时推送'), ('disabled', '不推送')], default='always', max_length=20, verbose_name='推送策略'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='push_message_content',
            field=models.TextField(blank=True, default='', help_text='Markdown格式，支持{{变量}}', verbose_name='推送消息内容'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='webhook_addresses',
            field=models.ManyToManyField(blank=True, help_text='订阅的飞书 Webhook 推送地址', related_name='scheduled_tasks', to='notifications.webhookaddress', verbose_name='推送地址'),
        ),
    ]
