# Generated by Django 5.2 on 2026-07-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ui_automation', '0003_appuibatchexecutionrecord_appuidevice_and_more'),
        ('task_center', '0007_scheduledtask_environment_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='app_ui_device',
            field=models.ForeignKey(blank=True, help_text='APPUI自动化执行时使用的设备', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_ui_automation.appuidevice', verbose_name='APPUI 执行设备'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='app_ui_scripts',
            field=models.ManyToManyField(blank=True, help_text='模块为"APPUI自动化"时选择要执行的脚本（串行执行）', related_name='scheduled_tasks', to='app_ui_automation.appuiscript', verbose_name='关联APPUI脚本'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='module',
            field=models.CharField(choices=[('ui_automation', 'UI 自动化'), ('test_suite', '测试套件'), ('app_ui_automation', 'APPUI 自动化')], max_length=20, verbose_name='所属模块'),
        ),
    ]
