# Generated by Django 5.2 on 2026-07-08 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ui_automation', '0002_appuiscript'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUiBatchExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='批次名称')),
                ('total_scripts', models.IntegerField(default=0, verbose_name='脚本总数')),
                ('passed_scripts', models.IntegerField(default=0, verbose_name='成功数')),
                ('failed_scripts', models.IntegerField(default=0, verbose_name='失败数')),
                ('status', models.SmallIntegerField(choices=[(0, '待执行'), (1, '执行中'), (2, '全部成功'), (3, '部分失败'), (4, '全部失败')], default=0, verbose_name='状态')),
                ('trigger_type', models.CharField(choices=[('manual', '手动'), ('scheduled', '定时'), ('api', 'API')], default='manual', max_length=20, verbose_name='触发类型')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='总时长（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_ui_batch_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': 'APPUI 批量执行记录',
                'verbose_name_plural': 'APPUI 批量执行记录',
                'db_table': 'app_ui_batch_execution_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppUiDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：测试机-小米12', max_length=100, verbose_name='设备名称')),
                ('connection_type', models.CharField(choices=[('adb_tcp', 'ADB TCP 远程'), ('emulator', 'Android 模拟器'), ('cloud', '云真机平台'), ('usb', 'USB 直连')], default='adb_tcp', max_length=20, verbose_name='连接类型')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10, verbose_name='平台')),
                ('device_uri', models.CharField(help_text='Android: android://127.0.0.1:5037/序列号; iOS: ios:///127.0.0.1:8100', max_length=500, verbose_name='设备连接URI')),
                ('device_serial', models.CharField(blank=True, default='', max_length=255, verbose_name='设备序列号')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('busy', '忙碌')], default='offline', max_length=10, verbose_name='设备状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='设备描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_ui_devices', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_ui_devices', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'APPUI 设备',
                'verbose_name_plural': 'APPUI 设备',
                'db_table': 'app_ui_device',
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AppUiExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '等待中'), (1, '执行中'), (2, '成功'), (3, '失败'), (4, '取消')], default=0, verbose_name='执行状态')),
                ('trigger_type', models.CharField(choices=[('manual', '手动'), ('scheduled', '定时'), ('api', 'API'), ('debug', '调试')], default='manual', max_length=20, verbose_name='触发类型')),
                ('total_steps', models.IntegerField(default=0, verbose_name='总步骤数')),
                ('passed_steps', models.IntegerField(default=0, verbose_name='通过步骤数')),
                ('failed_steps', models.IntegerField(default=0, verbose_name='失败步骤数')),
                ('report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='报告文件路径')),
                ('log_dir', models.CharField(blank=True, default='', max_length=500, verbose_name='日志目录路径')),
                ('execution_log', models.TextField(blank=True, null=True, verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行时长（秒）')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='app_ui_automation.appuibatchexecutionrecord', verbose_name='所属批次')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='app_ui_automation.appuidevice', verbose_name='执行设备')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_ui_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='app_ui_automation.appuiscript', verbose_name='执行脚本')),
            ],
            options={
                'verbose_name': 'APPUI 执行记录',
                'verbose_name_plural': 'APPUI 执行记录',
                'db_table': 'app_ui_execution_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
