# Generated by Django 5.2.13 on 2026-04-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationlog',
            options={'ordering': ['-created_at'], 'permissions': [('view_operation_logs', '查看操作日志'), ('manage_operation_logs', '管理操作日志'), ('export_operation_logs', '导出操作日志'), ('delete_operation_logs', '删除操作日志')], 'verbose_name': '操作日志', 'verbose_name_plural': '操作日志'},
        ),
    ]
